# sudo: required
sudo: false
dist: trusty
language: csharp
mono:
  - latest
solution: Everest.sln
script:
    - chmod a+x ./travis/replace-version.sh
    - ./travis/replace-version.sh
    - msbuild /p:TravisCore=true /p:Configuration=Release
after_success:
    - chmod a+x ./travis/travis-release.sh
    - ./travis/travis-release.sh